org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
GROUP=io.github.arjangconsulting
VERSION_NAME=0.0.0-SNAPSHOT
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/ArjangConsulting/android-network-recorder
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/ArjangConsulting/android-network-recorder
POM_SCM_CONNECTION=scm:git:git://github.com/ArjangConsulting/android-network-recorder.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/ArjangConsulting/android-network-recorder.git
POM_DEVELOPER_ID=ArjangConsulting
POM_DEVELOPER_NAME=Arjang Consulting
POM_DEVELOPER_URL=https://github.com/ArjangConsulting
